export const imagePaths: readonly string[] = [
  `image01.jpg`,
  `image02.jpg`,
  `image03.jpg`,
  `image04.jpg`,
  `image05.jpg`,
  `image06.jpg`,
  `image07.jpg`,
  `image08.jpg`,
  `image09.jpg`,
  `image10.jpg`,
  `image11.jpg`,
  `image12.jpg`,
  `image13.jpg`,
  `image14.jpg`,
];
